ls -aR "./test-project/android"
echo "========================1" 
ls -aR "opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" 
echo "========================2"
ls -aR "opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/SDK" 
echo "========================3"
