name: Cleanup (cron)
on:
  schedule:
    - cron: '31 16 * * TUE' # every sunday at 10:30

jobs:
  deleteArtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 21 days
